minimumReleaseAge: 0
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200

publicHoistPattern:
  - '*eslint-plugin-*'
  - '@typescript-eslint/eslint-plugin'
  - '@antfu/*'

shellEmulator: true

allowBuilds:
  esbuild: true
  vue-demi: true
